name: CI

on:
  push:
    branches: [master, beta]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: install dependencies
        run: yarn --frozen-lockfile
      - name: lint
        run: yarn lint

  test:
    name: Testing
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: install dependencies
        run: yarn --frozen-lockfile
      - name: test
        run: yarn test

  release:
    name: Building and releasing project
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
      - name: install dependencies
        run: yarn --frozen-lockfile
      - name: build
        run: |
          yarn build:ts
          sed 's/dist\//.\//' package.json > dist/package.json
          cp README.md dist/README.md
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.ASSOCIATION_NPM_TOKEN }}
        run: |
          cd dist
          yarn --frozen-lockfile
          yarn semantic-release
